<?php
  echo "        <footer class=\"footer\">\n";
  echo "          <div class=\"footer__block block no-margin-bottom\">\n";
  echo "            <div class=\"container-fluid text-center\">\n";
  echo "              <!-- Please do not remove the backlink to us unless you support us at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->\n";
  echo "              <p class=\"no-margin-bottom\">$surp_sitecr | Dise&ntilde;o por <a href=\"https://bootstrapious.com\" target=\"_new\">Bootstrapious</a>.</p>\n";
  echo "            </div>\n";
  echo "          </div>\n";
  echo "        </footer>\n";
  echo "      </div>\n";
  echo "    </div>\n";
  echo "    <!-- JavaScript files-->\n";
  echo "    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n";
  echo "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js\"> </script>\n";
  echo "    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\n";
  echo "    <script src=\"vendor/jquery.cookie/jquery.cookie.js\"> </script>\n";
  // echo "    <script src=\"vendor/chart.js/Chart.min.js\"></script>\n";
  // echo "    <script src=\"js/charts-home.js\"></script>\n";
  echo "    <script src=\"js/front.js\"></script>\n";
  echo "  </body>\n";
  echo "</html>\n";
