<?php
  echo "<!DOCTYPE html>\n";
  echo "<html>\n";
  echo "  <head> \n";
  // echo "    <meta charset=\"utf-8\">\n";
  echo "    <meta charset=\"iso-8859-1\" />\n";
  echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
  echo "    <title>.: $surp_sitename v.$surp_sitever :.</title>\n";
  echo "    <meta name=\"description\" content=\"$surp_siteslogan\">\n";
  echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
  echo "    <meta name=\"publisher\" content=\"UPB La Paz\" />\n";
  echo "    <meta name=\"copyright\" content=\"$surp_sitecr\" />\n";
  echo "    <meta name=\"author\" content=\"Carlos Anibarro <carlosanibarro(at)lp(dot)upb(dot)edu>\" />\n";
  echo "    <meta name=\"distribution\" content=\"IU\" />\n";
  // This is a private script, don't want follows
  echo "    <meta name=\"robots\" content=\"NoIndex, NoFollow\">\n";
  // echo "    <!-- Bootstrap CSS-->\n";
  echo "    <link rel=\"stylesheet\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\n";
  // echo "    <!-- Font Awesome CSS-->\n";
  echo "    <link rel=\"stylesheet\" href=\"vendor/font-awesome/css/font-awesome.min.css\">\n";
  // echo "    <!-- Custom Font Icons CSS-->\n";
  echo "    <link rel=\"stylesheet\" href=\"css/font.css\">\n";
  // echo "    <!-- Google fonts - Muli-->\n";
  echo "    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Muli:300,400,700\">\n";
  // echo "    <!-- theme stylesheet-->\n";
  echo "    <link rel=\"stylesheet\" href=\"css/style.upb.css\" id=\"theme-stylesheet\">\n";
  // echo "    <!-- Custom stylesheet - for your changes-->\n";
  echo "    <link rel=\"stylesheet\" href=\"css/custom.css\">\n";
  // echo "    <!-- Favicon-->\n";
  echo "    <link rel=\"shortcut icon\" href=\"img/favicon.ico\">\n";
  echo "    <!-- Tweaks for older IEs--><!--[if lt IE 9]>\n";
  echo "        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n";
  echo "        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script><![endif]-->\n";
  include_once("$pathinc/rightclick.inc.php");
  echo "  </head>\n";
  echo "  <body>\n";
  echo "    <header class=\"header\">   \n";
  echo "      <nav class=\"navbar navbar-expand-lg\">\n";
  echo "        <div class=\"container-fluid d-flex align-items-center justify-content-between\">\n";
  echo "          <div class=\"navbar-header\"><a href=\"index.html\" class=\"navbar-brand\">\n";
  echo "              <div class=\"brand-text brand-big visible text-uppercase\"><strong class=\"text-primary\">UPB</strong><strong>root</strong></div>\n";
  echo "              <div class=\"brand-text brand-sm\"><strong class=\"text-primary\">U</strong><strong>r</strong></div></a>\n";
  echo "            <button class=\"sidebar-toggle\"><i class=\"fa fa-long-arrow-left\"></i></button>\n";
  echo "          </div>\n";
  echo "          <ul class=\"right-menu list-inline no-margin-bottom\">    \n";
  echo "             $surv_user_name <i class=\"icon-user\"></i> | ";
  echo "            <li class=\"list-inline-item logout\">                   <a id=\"logout\" href=\"$PHPSELF?action=logout\" class=\"nav-link\">$l_logout <i class=\"icon-logout\"></i></a></li>\n";
  echo "          </ul>\n";
  echo "        </div>\n";
  echo "      </nav>\n";
  echo "    </header>\n";
  echo "    <div class=\"d-flex align-items-stretch\">\n";
  include_once("$pathinc/menu.inc.php");
  echo "      <div class=\"page-content\">\n";
